### PR TITLE
update deps, regenerate, & migrate to tree-sitter.json

### PR DESCRIPTION
**Pull request by amaanq**
The CLI version used to generate the grammar was bugged when it came to the inherits field - this bug, which was remedied a while ago, causes a panic now on the latest master, so I'm putting this PR up to fix it and bump the dependencies. We also now use a dedicated config file instead of a tree-sitter section in package.json (see the docs for more info) so I migrated that for you as well. Thanks!

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Thanks a ton for this PR <3

**Comment by amaanq** [comment]
🤔 do you think you'd be able to get this in? The CI failure looks unrelated to my changes

**Comment by NullVoxPopuli** [comment]
The linter is breaking. hmm.

All I'm doing is:
```
nvim -l scripts/format-queries.lua
```

**Comment by amaanq** [comment]
Not sure why it doesn't work. In any case, I didn't change any query files, so I don't think that's necessary for this PR.

**Comment by amaanq** [comment]
nice, seems to pass now.

**Pull request merged**
